version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/jupyter-hub"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/jupyter-datascience-notebook"
    schedule:
      interval: "weekly"
