apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jupyter-hub-deployment
  labels:
    app: jupyter-hub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-hub-deployment
  template:
    metadata:
      labels:
        app: jupyter-hub-deployment
    spec:
      containers:
      - name: jupyter-hub
        image: docker.io/derekpedersen/jupyter-hub:%GIT_COMMIT_SHA%
        ports:
        - containerPort: 8000    
        - containerPort: 8081
        resources:
          limits:
            cpu: "75m"
            memory: "500Mi"
          requests:
            cpu: "10m"
            memory: "250Mi"        
        env:
        - name: OAUTH_CALLBACK_URL
          value: https://jupyter.derekpedersen.io/hub/oauth_callback
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: jupyter-hub-config
              key: oauth_client_id
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: jupyter-hub-config
              key: oauth_client_secret