apiVersion: v1
kind: Secret
metadata:
  name: do-spaces-baseball
type: Opaque
stringData:
  bucket: "your-spaces-bucket"
  region: "nyc3"
  endpoint: "https://nyc3.digitaloceanspaces.com"
  access_key_id: "replace-me"
  secret_access_key: "replace-me"
